import { apiClient, ApiResponse } from './client'
import { BASE_URL } from './config'


const API = {
  instituteMaster:        (id: string) => `/institutes/${id}`,
  instituteBasicInfo:     (id: string) => `/institute-basic-info/institute/${id}`,
  instituteDetailsMaster: (id: string) => `/institute-details-master/institute/${id}`,
  instituteDocuments:     (id: string) => `/institute-documents/institute/${id}`,
  subscriptionTxn:        (id: string) => `/subscription-transactions/institute/${id}`,
  getAllAdminsByInstitute: (id: string) => `/institute-admin/get-by-institute/${id}`,
  createAdmin:            '/institute-admin/create',
  updateAdmin:            (id: string) => `/institute-admin/update/${id}`,
  deleteAdmin:            (id: string) => `/institute-admin/delete/${id}`,
}

// ─── institutes_master collection ────────────────────────────────────────────
// Verified against: institutesMasterSchema
// timestamps: true → createdAt / updatedAt auto-generated by Mongoose
export interface InstituteMaster {
  _id: string
  institute_code: string
  institute_name: string
  // Backend enum: 'school' | 'coaching' | 'both'
  institute_type: 'school' | 'coaching' | 'both'
  // Backend enum: 'pending_activation' | 'trial' | 'active' | 'suspended' | 'blocked' | 'expired' | 'archived'
  status: 'pending_activation' | 'trial' | 'active' | 'suspended' | 'blocked' | 'expired' | 'archived'
  application_reference_id?: string
  createdAt?: string
  updatedAt?: string
}

// ─── institute_basic_information collection ───────────────────────────────────
// Verified against: instituteBasicInformationSchema
// timestamps: true → createdAt / updatedAt
// NOT in schema: alternate_mobile, website, city, state, pincode, country
export interface InstituteBasicInfo {
  _id: string
  institute_id: string | object
  owner_name: string
  designation?: string
  email: string
  mobile: string
  address?: string
  email_verified?: boolean
  mobile_verified?: boolean
  createdAt?: string
  updatedAt?: string
}

// ─── institute_details collection ────────────────────────────────────────────
// Verified against: instituteDetailsSchema
// NOT in schema: affiliation_number, recognition_number, established_year, campus_area, facilities
export interface InstituteDetailsMaster {
  _id: string
  institute_id: string | object
  school_board?: string
  school_type?: 'private' | 'government' | 'public'
  classes_offered?: string[]
  courses_offered?: string[]
  medium?: 'english' | 'hindi' | 'other'
  // Backend enum: '1-100' | '101-250' | '251-500' | '500-1000' | '1000+'
  approx_students_range?: '1-100' | '101-250' | '251-500' | '500-1000' | '1000+'
  createdAt?: string
  updatedAt?: string
}

// ─── subscription_plan_variants collection ────────────────────────────────────
// Verified against: subscriptionPlanVariantSchema
// price / discount_percentage: Decimal128 in DB → serialized as Number via toJSON transform
// discounted_price: virtual field — present in toJSON response but not stored
// features: Object field — included
export interface SubscriptionPlanVariant {
  _id: string
  plan_master_id: string
  applicable_for: 'school' | 'coaching' | 'both'
  price: number
  discount_percentage: number
  discounted_price?: number   // virtual — may not always be present
  features?: Record<string, unknown>
  is_active: boolean
  createdAt?: string
  updatedAt?: string
}

// ─── institute_subscription_transactions collection ───────────────────────────
// Verified against: instituteSubscriptionTransactionsSchema
// Fix: payment_status backend enum is 'success' | 'failed' | 'refunded'
//      ('pending' does NOT exist in backend — was wrong in previous version)
// amount: Decimal128 → serialized as Number via toJSON transform
// subscription_plan_variant_id: populated ObjectId → SubscriptionPlanVariant | null
//   (if not populated it will be a string; guard with typeof check before using .applicable_for)
export interface SubscriptionTransaction {
  _id: string
  institute_id: string | object
  subscription_plan_variant_id: SubscriptionPlanVariant | string | null
  amount: number
  payment_status: 'success' | 'failed' | 'refunded'
  payment_gateway?: string
  transaction_id?: string
  receipt_url?: string
  paid_at?: string
  subscription_start_date?: string
  subscription_end_date?: string
  is_active: boolean
  createdAt?: string
  updatedAt?: string
}

// ─── Helper: safe plan name from variant ─────────────────────────────────────
// Guards against subscription_plan_variant_id being an unpopulated ObjectId string
export function getPlanName(
  variantOrId: SubscriptionPlanVariant | string | null | undefined
): string {
  if (!variantOrId) return '—'
  // If backend didn't populate the ref, it's just a string ID
  if (typeof variantOrId === 'string') return '—'
  switch (variantOrId.applicable_for) {
    case 'coaching': return 'Coaching Plan'
    case 'school':   return 'School Plan'
    case 'both':     return 'School & Coaching Plan'
    default:         return variantOrId.applicable_for
  }
}

// ─── institute_admins collection ──────────────────────────────────────────────
// Verified against: instituteAdminSchema
// NOT in schema: role, permissions
// is_first_login: has default: true — not truly optional, but API response may omit it
// otp / otp_expiry / password_hash / password_key — internal fields, never sent to frontend
export interface InstituteAdmin {
  _id: string
  institute_id: string | {
    _id: string
    institute_code: string
    institute_name: string
    institute_type: string
    status: string
  }
  name: string
  email: string
  mobile: string
  is_first_login: boolean
  last_login_at: string | null
  status: 'active' | 'blocked' | 'disabled'
  // Backend uses custom timestamps: created_at / updated_at (not createdAt/updatedAt)
  created_at?: string
  updated_at?: string
}

export interface CreateAdminPayload {
  institute_id: string
  name: string
  email: string
  mobile: string
  status?: 'active' | 'blocked' | 'disabled'
  // NOT included: password (auto-generated by backend), role, permissions (not in schema)
}

export interface UpdateAdminPayload {
  name?: string
  email?: string
  mobile?: string
  status?: 'active' | 'blocked' | 'disabled'
}

// ─── Aggregated settings data shape ──────────────────────────────────────────
export interface InstituteSettingsData {
  logo_url: string | null
  master: InstituteMaster | null
  basic_info: InstituteBasicInfo | null
  details: InstituteDetailsMaster | null
  subscription: SubscriptionTransaction | null
}

// ─── Settings API ─────────────────────────────────────────────────────────────
export const settingsApi = {
  getInstituteData: async (): Promise<InstituteSettingsData> => {
    const instituteId = typeof window !== 'undefined'
      ? localStorage.getItem('instituteId') : null
    if (!instituteId) throw new Error('Institute ID not found in localStorage')

    const [masterRes, basicInfoRes, detailsRes, subscriptionRes, docsRes] = await Promise.allSettled([
      apiClient.get<InstituteMaster>(API.instituteMaster(instituteId)),
      apiClient.get<InstituteBasicInfo>(API.instituteBasicInfo(instituteId)),
      apiClient.get<InstituteDetailsMaster>(API.instituteDetailsMaster(instituteId)),
      apiClient.get<SubscriptionTransaction[]>(API.subscriptionTxn(instituteId)),
      apiClient.get<{ document_type: string; file_url: string }[]>(API.instituteDocuments(instituteId)),
    ])

    const master = masterRes.status === 'fulfilled' && masterRes.value.success
      ? (masterRes.value.result ?? null) : null

    const basic_info = basicInfoRes.status === 'fulfilled' && basicInfoRes.value.success
      ? (basicInfoRes.value.result ?? null) : null

    const details = detailsRes.status === 'fulfilled' && detailsRes.value.success
      ? (detailsRes.value.result ?? null) : null

    let subscription: SubscriptionTransaction | null = null
    if (subscriptionRes.status === 'fulfilled' && subscriptionRes.value.success) {
      const list = subscriptionRes.value.result
      if (Array.isArray(list) && list.length > 0) subscription = list[0]
    }

    let logo_url: string | null = null
    if (docsRes.status === 'fulfilled' && docsRes.value.success) {
      const docs = docsRes.value.result
      if (Array.isArray(docs)) {
        // document_type enum verified: 'registration_certificate' | 'affiliation_certificate' | 'gst_certificate' | 'logo'
        const logoDoc = docs.find((d) => d.document_type === 'logo')
        if (logoDoc?.file_url) {
          logo_url = `${BASE_URL}${logoDoc.file_url}`
          // Sidebar ko fresh logo dikhane ke liye localStorage sync karo
          if (typeof window !== 'undefined') {
            localStorage.setItem('instituteLogo', logo_url)
            window.dispatchEvent(new Event('admin-profile-updated'))
          }
        }
      }
    }

    return { master, basic_info, details, subscription, logo_url }
  },

  getAdminsByInstitute: (): Promise<ApiResponse<InstituteAdmin[]>> => {
    const instituteId = typeof window !== 'undefined'
      ? localStorage.getItem('instituteId') : ''
    if (!instituteId) return Promise.reject(new Error('Institute ID not found in localStorage'))
    return apiClient.get<InstituteAdmin[]>(API.getAllAdminsByInstitute(instituteId))
  },

  createAdmin: (data: CreateAdminPayload): Promise<ApiResponse<InstituteAdmin>> => {
    return apiClient.post<InstituteAdmin>(API.createAdmin, data)
  },

  updateAdmin: (id: string, data: UpdateAdminPayload): Promise<ApiResponse<InstituteAdmin>> => {
    return apiClient.put<InstituteAdmin>(API.updateAdmin(id), data)
  },

  deleteAdmin: (id: string): Promise<ApiResponse<{ message: string }>> => {
    return apiClient.delete<{ message: string }>(API.deleteAdmin(id))
  },
}

